package de.tobiasroeser.maven.versionupdater;

// Class generated by cmvn
public abstract class BuildConfig {

	public static String mvuVersion() {
		return "0.1.1-SNAPSHOT";
	}

	public static String mvuCopyright() {
		return "(c) 2009-2011 by Tobias Roeser, All Rights Reserved.";
	}

}
