package de.tobiasroeser.maven.versionupdater;

// Class generated by cmvn
public abstract class BuildConfig {

	public static String mvuVersion() {
		return "0.1.1-SNAPSHOT";
	}

	public static String mvuCopyright() {
		return "(c) 2009-2015 by Tobias Roeser, Apache License, Version 2";
	}

}
