= Maven Version Updater
:author: Tobias Roeser
:mvu-version: 0.1.0
:mvu: Maven Version Updater
:toc:
:toc-placement: preamble

This Handbook describes {mvu} in version {mvu-version}.

== Features

=== Existing Features

* operate on many projects and multiprojects, even if they are not part of the same reactor
* extracts easily and fast information about used dependencies and their versions
* bulk change of many or all dependency versions
* bulk align of versions of dependencies to the local available artifacts/projects

=== Future Features

* trick Maven and use non-transitive build classpathes, e.g. generate `pom.xml` with a lot of exclusions for each dependency
* bulk change dependency artifacts
* more generic search options
* convert local dependencies to system dependencies which point to the local available jars directly to avoid an additional install step, and vice versa

=== Motivation (Maven sortcommings)

* Using Maven's -SNAPSHOT qualifiers is inconsistently handled by Maven and not compatible to OSGi Versioning.
* Using Maven's release plugin is no option, e.g. because it uses -SNAPSHOT version qualifiers and wants to rule the SCM and Maven remote repository.
* Therefore, there are no tools for efficient version management
* Maven is slow

== Previous Releases

=== Compatibility to {mvu} 0.0.x

Many commands line options have changed especially for searching, listing and filtering.

== Usage

=== Shell wrapper

I created an executable jar with dependencies. For convenience, you can create a simple shell script as an executable wrapper around the program:

.Shell wrapper `mvu` (Linux version)
[source,sh]
----
user@dev ~/work $ cat > ~/bin/mvu << "EOF"
#!/bin/sh
exec java -jar maven-version-updater-0.0.3-executable.jar $@
EOF
user@dev ~/work $ chmod +x ~/bin/mvu
----


=== Windows Command Shell Wrapper

.Windows Command Shell wrapper `mvn.bat`
[source,bat]
----
:init
@REM Decide how to startup depending on the version of windows

@REM -- Windows NT with Novell Login
if "%OS%"=="WINNT" goto WinNTNovell

@REM -- Win98ME
if NOT "%OS%"=="Windows_NT" goto Win9xArg

:WinNTNovell

@REM -- 4NT shell
if "%@eval[2+2]" == "4" goto 4NTArgs

@REM -- Regular WinNT shell
set MAVEN_CMD_LINE_ARGS=%*
goto endInit

@REM The 4NT Shell from jp software
:4NTArgs
set MAVEN_CMD_LINE_ARGS=%$
goto endInit

:Win9xArg
@REM Slurp the command line arguments.  This loop allows for an unlimited number
@REM of agruments (up to the command line limit, anyway).
set MAVEN_CMD_LINE_ARGS=
:Win9xApp
if %1a==a goto endInit
set MAVEN_CMD_LINE_ARGS=%MAVEN_CMD_LINE_ARGS% %1
shift
goto Win9xApp

@REM Reaching here means variables are defined and arguments have been captured
:endInit
SET MAVEN_JAVA_EXE="%JAVA_HOME%\bin\java.exe"

%MAVEN_JAVA_EXE% -jar maven-version-updater-0.0.3-executable.jar %MAVEN_CMD_LINE_ARGS%

set MAVEN_JAVA_EXE=
set MAVEN_CMD_LINE_ARGS=
----

=== Built-in help

Then you can run it like this:

.Output of `mvu --help`
----
user@dev ~/work $ mvu --help
Maven Version Updater 0.1.0 - (c) 2009-2010 by Tobias Roeser, All Rights Reserved.
Options: 
--align-local-dep-version PAR          Sync version of dependants to local project PAR (supports ${dryrun})
--apply-project-deps PAR1 PAR2         Update the project PAR1 with the dependencies from file PAR2
--check-artifact-list PAR              Compare a list of artifacts PAR with the real existing artifacts locally found.
--detect-local-version-mismatch        Detect project that depedend on other local project but with wrong version number
--directory, -d PAR                    Search maven project in directory PAR. If not given at least once, the current directory will be searched.
--dryrun                               Do not modify any project file
--exact                                When searching, only match exactly the same artifact keys
--extract-project-deps PAR1 PAR2       Extract the project dependencies of the given project PAR1 and write them to file PAR2
--filter-local true|false              Filter (when given) search to include/exclude local dependencies
--filter-system true|false             Filter (when given) search to include/exclude system dependencies
--list-artifacts                       List all found artifacts
--list-dependencies                    List add found dependencies
--list-deps-and-dependants             List all found dependencies and their dependants
--persist-artifact-list PAR            Write a list of found local artifacts (supports ${dryrun})
--replace-dependency PAR1 PAR2         Replace dependency PAR1 by dependency PAR2
--search-artifacts PAR                 Search for artifact(s) with pattern PAR (supports ${exactMatch})
--search-dependencies PAR              Search for dependency(s) with pattern PAR (supports ${exactMatch})
--set-dep-version PAR                  Updates the versions of all matching dependencies to dependencies PAR (supports ${dryrun})
--update-artifact-and-dep-version PAR  Upadte the artifact and all dependencies to that artifact to version PAR (same as ${updateArtifactVersion} and ${setDepVersion} used together)
--update-artifact-version PAR          Update the version of the matching artifact to artifact PAR (supports ${dryrun})
----

=== Workspace

The default workspace of {mvu} is the current working directory. You can specify the workspace with the commandline option `-d`. It is valid to specify more than one directory by using `-d` multiple times. In each of the given workspace directory {mvu} will take the \pom{} file into account. For multiprojects (`pom.xml`s with `<module>` tags) all subprojects (modules) will be used.

=== Finding and Searching

=== Scanning for version mismatches

For larger project workspaces or multproject setups, it is common that a lot of the projects are simultaniously dependencies of other local projects. In most cases, you want to use exactly those latest local available artifacts as dependants. Maintaining the versions of those dependencies in all of your \pom{} files can be a cumbersome task, especially, if you can not or do not want to use Maven's release plugin.

{mvu} can scan arbitrary sets of projects (including multiprojects) and detect those dependencies that depends on a different version than a possibly local available project provides.

.Scan for local version mismatches
----
user@dev ~/work $ mvu --detect-local-version-mismatch
[INFO] Scanning for projects based on: [.]
[INFO] Analyzing dependencies...
----

=== Fixing version mismatches

== Limitations

* No fully support for parent pom's
* No support for profiles, esp. dependencies that are declared in profiles
* No support for xxxManagement-sections like `dependencyManagement` or `pluginsManagement`


Most of these limitation are by purpose, as they belong to maven features which itselfs make reliable and reproducable build hard.

== Licence

This project is licensed under the http://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].
